package com.ecom.netcart.entity; // Package declaration

import jakarta.persistence.Entity; // Importing JPA Entity annotation
import jakarta.persistence.GeneratedValue; // Importing JPA GeneratedValue annotation
import jakarta.persistence.GenerationType; // Importing JPA GenerationType enum
import jakarta.persistence.Id; // Importing JPA Id annotation
import jakarta.persistence.OneToMany; // Importing JPA OneToMany annotation
import lombok.Data; // Importing Lombok Data annotation

import java.util.List; // Importing List interface
import java.util.ArrayList; // Importing ArrayList class

/**
 * Represents a category in the e-commerce application.
 * Each category can have multiple products associated with it.
 */
@Data // Lombok annotation to generate getters, setters, toString, equals, and hashCode methods
@Entity // Specifies that the class is an entity and is mapped to a database table
public class Category {

    @Id // Specifies the primary key of an entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Provides the specification of generation strategies for the values of primary keys
    private Integer categoryId; // Unique identifier for the category

    private String categoryTitle; // Title of the category

    private String categoryDescription; // Description of the category

    @OneToMany(mappedBy = "category") // Specifies a one-to-many relationship with the Product entity
    private List<Product> products = new ArrayList<>(); // List of products in this category, initialized as an empty ArrayList

    // Default constructor, getters, setters, and other methods are generated by Lombok's @Data annotation
}
