package com.ecom.netcart.entity; // Package declaration

import java.util.List; // Importing List interface

import jakarta.persistence.CascadeType; // Importing JPA CascadeType enum
import jakarta.persistence.Entity; // Importing JPA Entity annotation
import jakarta.persistence.GeneratedValue; // Importing JPA GeneratedValue annotation
import jakarta.persistence.GenerationType; // Importing JPA GenerationType enum
import jakarta.persistence.Id; // Importing JPA Id annotation
import jakarta.persistence.OneToMany; // Importing JPA OneToMany annotation
import lombok.Data; // Importing Lombok Data annotation

/**
 * Represents a user in the e-commerce application.
 * Each user can have multiple orders associated with them.
 */
@Data // Lombok annotation to generate getters, setters, toString, equals, and hashCode methods
@Entity // Specifies that the class is an entity and is mapped to a database table
public class User {

    @Id // Specifies the primary key of an entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Provides the specification of generation strategies for the values of primary keys
    private Integer userId; // Unique identifier for the user

    private String username; // Username of the user

    private String password; // Password of the user

    private String email; // Email address of the user

    private String address; // Physical address of the user

    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL) // Specifies a one-to-many relationship with the Orders entity, with cascading all operations
    private List<Orders> order; // List of orders placed by the user

    // Default constructor, getters, setters, and other methods are generated by Lombok's @Data annotation
}
